# -*- coding: utf-8 -*-
"""Week 11 Tasks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqtwgbjYwGqpwbgC7iCJnHwLucDyMUnj
"""

!git clone https://github.com/SyedNasir512/tasks.git

# Commented out IPython magic to ensure Python compatibility.
# %cd tasks
!git pull https://github.com/SyedNasir512/tasks.git
!ls

!git config --global user.email "syed.nasir9841@gmail.com"
!git config --global user.name "SyedNasir512"

import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data = pd.read_csv('/content/heart-disease.csv')
X = data.drop('target', axis=1)
y= data['target']

data.head(6)

data.shape

#preprocessing
scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
#ANN Model
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

#compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
#train the model
model.fit(X_train, y_train, epochs=20, batch_size=64,validation_data=(X_test, y_test))
#Evaluate accuracy
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Accuracy: {accuracy * 100:.2f}%')

model.save("heart_prediction.keras")

# stage all changes
!git add .
# commit
!git commit -m "update things on google colab"

# Git Hub token
# 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
import getpass
username = "SyedNasir512"
token = getpass.getpass("Enter your Github persoanl token: ")

!git push https://{username}:{token}@github.com/SyedNasir512/tasks.git